### ISSUE TITLE
cannot resolve go.microsoft.com

### ISSUE THREAD

**Issue by Juphex** [pulla2908/docker-mssql-server-windows-developer-fti#2]
`Step 8/11 : RUN Invoke-WebRequest -Uri $env:box -OutFile SQL.box ;         Invoke-WebRequest -Uri $env:exe -OutFile 
SQL.exe ;         Start-Process -Wait -FilePath .\SQL.exe -ArgumentList /qs, /x:setup ;         .\setup\setup.exe /q /ACTION=Install /INSTANCENAME=MSSQLSERVER /FEATURES=SQLEngine /UPDATEENABLED=0 /SQLSVCACCOUNT='NT AUTHORITY\NETWORK SERVICE' /SQLSYSADMINACCOUNTS='BUILTIN\ADMINISTRATORS' /TCPENABLED=1 /NPENABLED=0 /IACCEPTSQLSERVERLICENSETERMS ;  
       Remove-Item -Recurse -Force SQL.exe, SQL.box, setup
 ---> Running in bcf508e67888
Invoke-WebRequest : The remote name could not be resolved: 'go.microsoft.com'
At line:1 char:76
+ ... lyContinue'; Invoke-WebRequest -Uri $env:box -OutFile SQL.box ; Invok ...
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:Htt
   pWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShe
   ll.Commands.InvokeWebRequestCommand`

**Comment by pulla2908** [comment]
sorry for late response. do you still get the error?

**Comment by pulla2908** [comment]
@Juphex I was able to reproduce. It seams to me it is about the host dns settings. while you build the image the dns in use can't resolve names.

There is an issue which describes this case: [https://github.com/docker/for-win/issues/427](url)

You could try to add following parameter when building the image:
`--network "Default Switch"`

Like this: 
`docker build -t mssql-server-windows-developer-fti . --network "Default Switch"`

Please tell me if that helps.

**Comment by kkbruce** [comment]
@pulla2908 
I have `docker build` problem, and try `--network "Default Switch"` is work for me.

**Comment by Juphex** [comment]
yes,  `--network "Default Switch"` works.
However, the container is then available in the network, so keep an eye out.

**Comment by pulla2908** [comment]
@kkbruce @Juphex thx for the feedback. I will document this in the readme
